remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
logo: ./assets/discord-a2s.png
title: ./discord-a2s-bot
description: Discord A2S Bot
markdown: GFM
github:
  zip_url: https://github.com/woozymasta/discord-a2s-bot/zipball/master
  tar_url: https://github.com/woozymasta/discord-a2s-bot/tarball/master
  linux: https://github.com/woozymasta/discord-a2s-bot/releases/latest/download/discord-a2s-bot-linux-amd64
  darwin: https://github.com/woozymasta/discord-a2s-bot/releases/latest/download/discord-a2s-bot-darwin-arm64
  windows: https://github.com/woozymasta/discord-a2s-bot/releases/latest/download/discord-a2s-bot-windows-amd64.exe
